-- MySQL Script generated by MySQL Workbench
-- Tue 17 Feb 2015 10:38:00 AM CST
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
-- -----------------------------------------------------
-- Schema posesio_app_user_
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `posesio_app_user_` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`propiedad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`propiedad` ;

CREATE TABLE IF NOT EXISTS `mydb`.`propiedad` (
  `id_propiedad` INT NOT NULL AUTO_INCREMENT,
  `ruta_foto` VARCHAR(255) NULL DEFAULT NULL,
  `nickname` VARCHAR(255) NOT NULL,
  `calle` VARCHAR(255) NOT NULL,
  `numero_exterior` VARCHAR(50) NOT NULL,
  `numero_interior` VARCHAR(45) NULL DEFAULT NULL,
  `colonia` VARCHAR(255) NOT NULL,
  `municipio` VARCHAR(255) NOT NULL,
  `estado` VARCHAR(255) NOT NULL,
  `codigo_postal` VARCHAR(10) NOT NULL,
  `pais` VARCHAR(255) NOT NULL,
  `nombre_propietario` VARCHAR(255) NULL DEFAULT NULL,
  `cta_predial` VARCHAR(50) NULL DEFAULT NULL,
  `metros_terreno` INT NULL DEFAULT NULL,
  `metros_construccion` INT NULL DEFAULT NULL,
  `costo_mantenimiento` DECIMAL(10,2) NULL DEFAULT NULL,
  `costo_predial` DECIMAL(10,2) NULL DEFAULT NULL,
  `comentarios` TEXT NULL DEFAULT NULL,
  `estatus` VARCHAR(50) NULL DEFAULT NULL,
  `activa` TINYINT(1) NULL DEFAULT NULL,
  `fecha_alta` DATE NULL DEFAULT NULL,
  `fecha_baja` DATE NULL DEFAULT NULL,
  `num_cuartos` VARCHAR(255) NULL DEFAULT NULL,
  `num_banos` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id_propiedad`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`contacto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`contacto` ;

CREATE TABLE IF NOT EXISTS `mydb`.`contacto` (
  `id_contacto` BIGINT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(255) NULL DEFAULT NULL,
  `apellido_paterno` VARCHAR(255) NULL DEFAULT NULL,
  `apellido_materno` VARCHAR(255) NULL DEFAULT NULL,
  `trabajo` VARCHAR(255) NULL DEFAULT NULL,
  `telefono` VARCHAR(15) NULL DEFAULT NULL,
  `celular` VARCHAR(15) NULL DEFAULT NULL,
  `oficina` VARCHAR(15) NULL DEFAULT NULL,
  `telefono_alterno` VARCHAR(15) NULL DEFAULT NULL,
  `celular_alterno` VARCHAR(15) NULL DEFAULT NULL,
  `oficina_alterno` VARCHAR(15) NULL DEFAULT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `email_alterno` VARCHAR(255) NULL DEFAULT NULL,
  `comentarios` VARCHAR(255) NULL DEFAULT NULL,
  `persona` VARCHAR(10) NULL DEFAULT NULL,
  `razon_social` VARCHAR(255) NULL DEFAULT NULL,
  `rfc` VARCHAR(13) NULL DEFAULT NULL,
  `calle` VARCHAR(255) NULL DEFAULT NULL,
  `numero_exterior` VARCHAR(50) NULL DEFAULT NULL,
  `numero_interior` VARCHAR(50) NULL DEFAULT NULL,
  `colonia` VARCHAR(255) NULL DEFAULT NULL,
  `municipio` VARCHAR(255) NULL DEFAULT NULL,
  `estado` VARCHAR(255) NULL DEFAULT NULL,
  `codigo_postal` VARCHAR(255) NULL DEFAULT NULL,
  `pais` VARCHAR(255) NULL DEFAULT NULL,
  `activo` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`id_contacto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`contrato`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`contrato` ;

CREATE TABLE IF NOT EXISTS `mydb`.`contrato` (
  `id_contrato` INT NOT NULL AUTO_INCREMENT,
  `propiedad_id_propiedad` INT NOT NULL,
  `contacto_id_contacto` BIGINT NOT NULL,
  `id_fiador` BIGINT NULL DEFAULT NULL,
  `validez_fiscal` TINYINT(1) NOT NULL,
  `fecha_inicio` DATE NOT NULL,
  `fecha_fin` DATE NOT NULL,
  `fecha_corte` DATE NOT NULL,
  `periodicidad` VARCHAR(255) NOT NULL,
  `adeudo_anterior` DECIMAL(15,2) NULL DEFAULT NULL,
  `monto` DECIMAL(15,2) NOT NULL,
  `tasa_iva` DECIMAL(15,2) NOT NULL,
  `iva` DECIMAL(15,2) NOT NULL,
  `subtotal` DECIMAL(15,2) NOT NULL,
  `retencion_isr` DECIMAL(15,2) NOT NULL,
  `retencion_iva` DECIMAL(15,2) NOT NULL,
  `total` DECIMAL(15,2) NOT NULL,
  `multa_moratoria` DECIMAL(15,2) NOT NULL,
  `dias_multa` INT NOT NULL,
  `tasa_interes` VARCHAR(45) NOT NULL,
  `dias_interes` INT NOT NULL,
  `porcentaje_tasa_interes` DECIMAL(10,2) NOT NULL,
  `activo` TINYINT(1) NOT NULL,
  `comentarios` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id_contrato`, `propiedad_id_propiedad`, `contacto_id_contacto`),
  INDEX `fk_contrato_propiedad1_idx` (`propiedad_id_propiedad` ASC),
  INDEX `fk_contrato_contacto1_idx` (`contacto_id_contacto` ASC),
  INDEX `fk_contrato_contacto2_idx` (`id_fiador` ASC),
  CONSTRAINT `fk_contrato_propiedad1`
    FOREIGN KEY (`propiedad_id_propiedad`)
    REFERENCES `mydb`.`propiedad` (`id_propiedad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contrato_contacto1`
    FOREIGN KEY (`contacto_id_contacto`)
    REFERENCES `mydb`.`contacto` (`id_contacto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contrato_contacto2`
    FOREIGN KEY (`id_fiador`)
    REFERENCES `mydb`.`contacto` (`id_contacto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`datos_fiscales`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`datos_fiscales` ;

CREATE TABLE IF NOT EXISTS `mydb`.`datos_fiscales` (
  `id_datos_fiscales` BIGINT NOT NULL AUTO_INCREMENT,
  `ruta_logo` VARCHAR(255) NULL DEFAULT NULL,
  `persona` VARCHAR(10) NULL DEFAULT NULL,
  `razon_social` VARCHAR(255) NULL DEFAULT NULL,
  `rfc` VARCHAR(13) NULL DEFAULT NULL,
  `calle` VARCHAR(255) NULL DEFAULT NULL,
  `numero_exterior` VARCHAR(50) NULL DEFAULT NULL,
  `numero_interior` VARCHAR(50) NULL DEFAULT NULL,
  `colonia` VARCHAR(255) NULL DEFAULT NULL,
  `municipio` VARCHAR(255) NULL DEFAULT NULL,
  `estado` VARCHAR(255) NULL DEFAULT NULL,
  `codigo_postal` VARCHAR(255) NULL DEFAULT NULL,
  `pais` VARCHAR(255) NULL DEFAULT NULL,
  `ruta_cer` VARCHAR(255) NULL DEFAULT NULL,
  `ruta_key` VARCHAR(255) NULL DEFAULT NULL,
  `llave_privada` VARCHAR(255) NULL DEFAULT NULL,
  `licencia` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id_datos_fiscales`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`recibo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`recibo` ;

CREATE TABLE IF NOT EXISTS `mydb`.`recibo` (
  `id_recibo` INT NOT NULL AUTO_INCREMENT,
  `contrato_id_contrato` INT NOT NULL,
  `contrato_propiedad_id_propiedad` INT NOT NULL,
  `contrato_contacto_id_contacto` BIGINT NOT NULL,
  `fecha_corte` DATETIME NOT NULL,
  `fecha_inicio_recibo` DATETIME NOT NULL,
  `fecha_fin_recibo` DATETIME NOT NULL,
  `monto` DECIMAL(15,2) NOT NULL,
  `tasa_iva` DECIMAL(15,2) NOT NULL,
  `iva` DECIMAL(15,2) NOT NULL,
  `subtotal` DECIMAL(15,2) NOT NULL,
  `retencion_isr` DECIMAL(15,2) NOT NULL,
  `retencion_iva` DECIMAL(15,2) NOT NULL,
  `total` DECIMAL(15,2) NOT NULL,
  `validez_fiscal` TINYINT(1) NOT NULL COMMENT 'No se refiere a el estatus de \"timbrada\" sino al hecho de si es una factura o un recibo \"normal\"',
  `no_cuenta` VARCHAR(45) NOT NULL DEFAULT 'No Identificado',
  `metodo_pago` VARCHAR(100) NOT NULL DEFAULT 'No Identificado',
  `fecha_update` DATETIME NOT NULL,
  `folio_factura` INT NULL DEFAULT NULL,
  `folio_recibo` INT NULL DEFAULT NULL,
  `estatus_recibo` TINYINT(1) NOT NULL COMMENT '0 sin pagar, 1 pagado',
  `cancelado` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id_recibo`, `contrato_id_contrato`, `contrato_propiedad_id_propiedad`, `contrato_contacto_id_contacto`),
  INDEX `fk_pago_contrato1_idx` (`contrato_id_contrato` ASC, `contrato_propiedad_id_propiedad` ASC, `contrato_contacto_id_contacto` ASC),
  CONSTRAINT `fk_pago_contrato1`
    FOREIGN KEY (`contrato_id_contrato` , `contrato_propiedad_id_propiedad` , `contrato_contacto_id_contacto`)
    REFERENCES `mydb`.`contrato` (`id_contrato` , `propiedad_id_propiedad` , `contacto_id_contacto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`concepto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`concepto` ;

CREATE TABLE IF NOT EXISTS `mydb`.`concepto` (
  `id_concepto` INT NOT NULL AUTO_INCREMENT,
  `recibo_id_recibo` INT NOT NULL,
  `recibo_contrato_id_contrato` INT NOT NULL,
  `recibo_contrato_propiedad_id_propiedad` INT NOT NULL,
  `recibo_contrato_contacto_id_contacto` BIGINT NOT NULL,
  `descripcion` VARCHAR(255) NOT NULL,
  `monto` DECIMAL(15,2) NOT NULL,
  PRIMARY KEY (`id_concepto`, `recibo_id_recibo`, `recibo_contrato_id_contrato`, `recibo_contrato_propiedad_id_propiedad`, `recibo_contrato_contacto_id_contacto`),
  INDEX `fk_concepto_recibo1` (`recibo_id_recibo` ASC, `recibo_contrato_id_contrato` ASC, `recibo_contrato_propiedad_id_propiedad` ASC, `recibo_contrato_contacto_id_contacto` ASC),
  CONSTRAINT `fk_concepto_recibo1`
    FOREIGN KEY (`recibo_id_recibo` , `recibo_contrato_id_contrato` , `recibo_contrato_propiedad_id_propiedad` , `recibo_contrato_contacto_id_contacto`)
    REFERENCES `mydb`.`recibo` (`id_recibo` , `contrato_id_contrato` , `contrato_propiedad_id_propiedad` , `contrato_contacto_id_contacto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`factura`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`factura` ;

CREATE TABLE IF NOT EXISTS `mydb`.`factura` (
  `recibo_id_recibo` INT NOT NULL,
  `recibo_contrato_id_contrato` INT NOT NULL,
  `recibo_contrato_propiedad_id_propiedad` INT NOT NULL,
  `recibo_contrato_contacto_id_contacto` BIGINT NOT NULL,
  `id_factura` BIGINT(20) NOT NULL,
  `xml` TEXT NOT NULL,
  `version` VARCHAR(3) NOT NULL,
  `folio` INT(50) NOT NULL,
  `uuid` TEXT NOT NULL,
  `rfc_emisor` VARCHAR(15) NOT NULL,
  `rfc_receptor` VARCHAR(15) NOT NULL,
  `total` DECIMAL(15,2) NOT NULL,
  `cadena_original` TEXT NOT NULL,
  `sello` TEXT NOT NULL,
  `qr` TEXT NOT NULL,
  PRIMARY KEY (`recibo_id_recibo`, `recibo_contrato_id_contrato`, `recibo_contrato_propiedad_id_propiedad`, `recibo_contrato_contacto_id_contacto`, `id_factura`),
  CONSTRAINT `fk_factura_recibo1`
    FOREIGN KEY (`recibo_id_recibo` , `recibo_contrato_id_contrato` , `recibo_contrato_propiedad_id_propiedad` , `recibo_contrato_contacto_id_contacto`)
    REFERENCES `mydb`.`recibo` (`id_recibo` , `contrato_id_contrato` , `contrato_propiedad_id_propiedad` , `contrato_contacto_id_contacto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pago`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`pago` ;

CREATE TABLE IF NOT EXISTS `mydb`.`pago` (
  `id_pago` BIGINT NOT NULL AUTO_INCREMENT,
  `recibo_id_recibo` INT NULL DEFAULT NULL,
  `recibo_contrato_id_contrato` INT NOT NULL,
  `recibo_contrato_propiedad_id_propiedad` INT NOT NULL,
  `recibo_contrato_contacto_id_contacto` BIGINT NOT NULL,
  `fecha_pago` DATETIME NOT NULL,
  `forma_pago` VARCHAR(45) NOT NULL,
  `banco` VARCHAR(100) NULL DEFAULT NULL,
  `num_cheque` VARCHAR(100) NULL DEFAULT NULL,
  `abono` DECIMAL(15,2) NOT NULL,
  `comentarios` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id_pago`, `recibo_contrato_id_contrato`, `recibo_contrato_propiedad_id_propiedad`, `recibo_contrato_contacto_id_contacto`),
  INDEX `fk_pago_recibo1` (`recibo_id_recibo` ASC, `recibo_contrato_id_contrato` ASC, `recibo_contrato_propiedad_id_propiedad` ASC, `recibo_contrato_contacto_id_contacto` ASC),
  CONSTRAINT `fk_pago_recibo1`
    FOREIGN KEY (`recibo_id_recibo` , `recibo_contrato_id_contrato` , `recibo_contrato_propiedad_id_propiedad` , `recibo_contrato_contacto_id_contacto`)
    REFERENCES `mydb`.`recibo` (`id_recibo` , `contrato_id_contrato` , `contrato_propiedad_id_propiedad` , `contrato_contacto_id_contacto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`duenos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`duenos` ;

CREATE TABLE IF NOT EXISTS `mydb`.`duenos` (
  `id_dueno` BIGINT NOT NULL AUTO_INCREMENT,
  `persona` VARCHAR(10) NULL DEFAULT NULL,
  `razon_social` VARCHAR(255) NULL DEFAULT NULL,
  `rfc` VARCHAR(13) NULL DEFAULT NULL,
  `calle` VARCHAR(255) NULL DEFAULT NULL,
  `numero_exterior` VARCHAR(50) NULL DEFAULT NULL,
  `numero_interior` VARCHAR(50) NULL DEFAULT NULL,
  `colonia` VARCHAR(255) NULL DEFAULT NULL,
  `municipio` VARCHAR(255) NULL DEFAULT NULL,
  `estado` VARCHAR(255) NULL DEFAULT NULL,
  `codigo_postal` VARCHAR(255) NULL DEFAULT NULL,
  `pais` VARCHAR(255) NULL DEFAULT NULL,
  `ruta_cer` VARCHAR(255) NULL DEFAULT NULL,
  `ruta_key` VARCHAR(255) NULL DEFAULT NULL,
  `llave_privada` VARCHAR(255) NULL DEFAULT NULL,
  `licencia` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id_dueno`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`usuario` ;

CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `email` VARBINARY(255) NOT NULL,
  `password` VARBINARY(255) NOT NULL,
  `forgot_pass` VARBINARY(255) NOT NULL,
  `nombre` VARBINARY(255) NOT NULL,
  `apellido_paterno` VARBINARY(255) NOT NULL,
  `apellido_materno` VARBINARY(255) NOT NULL,
  `db_version` INT NOT NULL DEFAULT 0,
  `fecha_reg` DATETIME NOT NULL,
  `fecha_mod` TIMESTAMP NOT NULL,
  `estatus` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  UNIQUE INDEX `forgot_pass_UNIQUE` (`forgot_pass` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`paquete`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`paquete` ;

CREATE TABLE IF NOT EXISTS `mydb`.`paquete` (
  `id_paquete` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `total_propiedades` INT NOT NULL,
  `estatus` TINYINT(1) NOT NULL DEFAULT 1,
  `fecha_reg` DATETIME NOT NULL,
  `fecha_mod` TIMESTAMP NOT NULL,
  `subscription_plan_id` VARCHAR(45) NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_paquete`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ci_sessions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`ci_sessions` ;

CREATE TABLE IF NOT EXISTS `mydb`.`ci_sessions` (
  `session_id` VARCHAR(40) NOT NULL DEFAULT '0',
  `ip_address` VARCHAR(45) NOT NULL DEFAULT '0',
  `user_agent` VARCHAR(120) NOT NULL,
  `last_activity` INT(10) UNSIGNED NOT NULL DEFAULT 0,
  `user_data` TEXT NOT NULL,
  PRIMARY KEY (`session_id`),
  INDEX `last_activity_idx` (`last_activity` ASC));


-- -----------------------------------------------------
-- Table `mydb`.`usuario_has_paquete`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`usuario_has_paquete` ;

CREATE TABLE IF NOT EXISTS `mydb`.`usuario_has_paquete` (
  `usuario_id_usuario` INT NOT NULL,
  `paquete_id_paquete` INT NOT NULL,
  `fecha_reg` DATETIME NOT NULL,
  `fecha_fin` DATETIME NULL DEFAULT NULL,
  `estatus` VARCHAR(100) NOT NULL,
  `token` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`usuario_id_usuario`, `paquete_id_paquete`),
  INDEX `fk_usuario_has_paquete_paquete1_idx` (`paquete_id_paquete` ASC),
  INDEX `fk_usuario_has_paquete_usuario_idx` (`usuario_id_usuario` ASC),
  CONSTRAINT `fk_usuario_has_paquete_usuario`
    FOREIGN KEY (`usuario_id_usuario`)
    REFERENCES `mydb`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_has_paquete_paquete1`
    FOREIGN KEY (`paquete_id_paquete`)
    REFERENCES `mydb`.`paquete` (`id_paquete`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `posesio_app_user_` ;

-- -----------------------------------------------------
-- Table `posesio_app_user_`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `posesio_app_user_`.`usuario` ;

CREATE TABLE IF NOT EXISTS `posesio_app_user_`.`usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `email` VARBINARY(255) NOT NULL,
  `password` VARBINARY(255) NOT NULL,
  `forgot_pass` VARBINARY(255) NOT NULL,
  `nombre` VARBINARY(255) NOT NULL,
  `apellido_paterno` VARBINARY(255) NOT NULL,
  `apellido_materno` VARBINARY(255) NOT NULL,
  `db_version` INT NOT NULL DEFAULT 0,
  `fecha_reg` DATETIME NOT NULL,
  `fecha_mod` TIMESTAMP NOT NULL,
  `estatus` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_usuario`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  UNIQUE INDEX `forgot_pass_UNIQUE` (`forgot_pass` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `posesio_app_user_`.`paquete`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `posesio_app_user_`.`paquete` ;

CREATE TABLE IF NOT EXISTS `posesio_app_user_`.`paquete` (
  `id_paquete` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `total_propiedades` INT NOT NULL,
  `estatus` TINYINT(1) NOT NULL DEFAULT 1,
  `fecha_reg` DATETIME NOT NULL,
  `fecha_mod` TIMESTAMP NOT NULL,
  `subscription_plan_id` VARCHAR(45) NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_paquete`),
  UNIQUE INDEX `nombre_UNIQUE` (`nombre` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `posesio_app_user_`.`ci_sessions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `posesio_app_user_`.`ci_sessions` ;

CREATE TABLE IF NOT EXISTS `posesio_app_user_`.`ci_sessions` (
  `session_id` VARCHAR(40) NOT NULL DEFAULT '0',
  `ip_address` VARCHAR(45) NOT NULL DEFAULT '0',
  `user_agent` VARCHAR(120) NOT NULL,
  `last_activity` INT(10) UNSIGNED NOT NULL DEFAULT 0,
  `user_data` TEXT NOT NULL,
  PRIMARY KEY (`session_id`),
  INDEX `last_activity_idx` (`last_activity` ASC));


-- -----------------------------------------------------
-- Table `posesio_app_user_`.`usuario_has_paquete`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `posesio_app_user_`.`usuario_has_paquete` ;

CREATE TABLE IF NOT EXISTS `posesio_app_user_`.`usuario_has_paquete` (
  `usuario_id_usuario` INT NOT NULL,
  `paquete_id_paquete` INT NOT NULL,
  `fecha_reg` DATETIME NOT NULL,
  `fecha_fin` DATETIME NULL DEFAULT NULL,
  `estatus` VARCHAR(100) NOT NULL,
  `token` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`usuario_id_usuario`, `paquete_id_paquete`),
  INDEX `fk_usuario_has_paquete_paquete1_idx` (`paquete_id_paquete` ASC),
  INDEX `fk_usuario_has_paquete_usuario_idx` (`usuario_id_usuario` ASC),
  CONSTRAINT `fk_usuario_has_paquete_usuario`
    FOREIGN KEY (`usuario_id_usuario`)
    REFERENCES `posesio_app_user_`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usuario_has_paquete_paquete1`
    FOREIGN KEY (`paquete_id_paquete`)
    REFERENCES `posesio_app_user_`.`paquete` (`id_paquete`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `posesio_app_user_`.`propiedad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `posesio_app_user_`.`propiedad` ;

CREATE TABLE IF NOT EXISTS `posesio_app_user_`.`propiedad` (
  `id_propiedad` INT NOT NULL AUTO_INCREMENT,
  `usuario_id_usuario` INT NOT NULL,
  `ruta_foto` VARCHAR(255) NULL DEFAULT NULL,
  `nickname` VARCHAR(255) NOT NULL,
  `calle` VARCHAR(255) NOT NULL,
  `numero_exterior` VARCHAR(50) NOT NULL,
  `numero_interior` VARCHAR(45) NULL DEFAULT NULL,
  `colonia` VARCHAR(255) NOT NULL,
  `municipio` VARCHAR(255) NOT NULL,
  `estado` VARCHAR(255) NOT NULL,
  `codigo_postal` VARCHAR(10) NOT NULL,
  `pais` VARCHAR(255) NOT NULL,
  `nombre_propietario` VARCHAR(255) NULL DEFAULT NULL,
  `cta_predial` VARCHAR(50) NULL DEFAULT NULL,
  `metros_terreno` INT NULL DEFAULT NULL,
  `metros_construccion` INT NULL DEFAULT NULL,
  `costo_mantenimiento` DECIMAL(10,2) NULL DEFAULT NULL,
  `costo_predial` DECIMAL(10,2) NULL DEFAULT NULL,
  `comentarios` TEXT NULL DEFAULT NULL,
  `estatus` VARCHAR(50) NULL DEFAULT NULL,
  `activa` TINYINT(1) NULL DEFAULT NULL,
  `fecha_alta` DATE NULL DEFAULT NULL,
  `fecha_baja` DATE NULL DEFAULT NULL,
  `num_cuartos` VARCHAR(255) NULL DEFAULT NULL,
  `num_banos` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id_propiedad`),
  INDEX `fk_propiedad_usuario1_idx` (`usuario_id_usuario` ASC),
  CONSTRAINT `fk_propiedad_usuario1`
    FOREIGN KEY (`usuario_id_usuario`)
    REFERENCES `posesio_app_user_`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `posesio_app_user_`.`contacto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `posesio_app_user_`.`contacto` ;

CREATE TABLE IF NOT EXISTS `posesio_app_user_`.`contacto` (
  `id_contacto` BIGINT NOT NULL AUTO_INCREMENT,
  `usuario_id_usuario` INT NOT NULL,
  `nombre` VARCHAR(255) NULL DEFAULT NULL,
  `apellido_paterno` VARCHAR(255) NULL DEFAULT NULL,
  `apellido_materno` VARCHAR(255) NULL DEFAULT NULL,
  `trabajo` VARCHAR(255) NULL DEFAULT NULL,
  `telefono` VARCHAR(15) NULL DEFAULT NULL,
  `celular` VARCHAR(15) NULL DEFAULT NULL,
  `oficina` VARCHAR(15) NULL DEFAULT NULL,
  `telefono_alterno` VARCHAR(15) NULL DEFAULT NULL,
  `celular_alterno` VARCHAR(15) NULL DEFAULT NULL,
  `oficina_alterno` VARCHAR(15) NULL DEFAULT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `email_alterno` VARCHAR(255) NULL DEFAULT NULL,
  `comentarios` VARCHAR(255) NULL DEFAULT NULL,
  `persona` VARCHAR(10) NULL DEFAULT NULL,
  `razon_social` VARCHAR(255) NULL DEFAULT NULL,
  `rfc` VARCHAR(13) NULL DEFAULT NULL,
  `calle` VARCHAR(255) NULL DEFAULT NULL,
  `numero_exterior` VARCHAR(50) NULL DEFAULT NULL,
  `numero_interior` VARCHAR(50) NULL DEFAULT NULL,
  `colonia` VARCHAR(255) NULL DEFAULT NULL,
  `municipio` VARCHAR(255) NULL DEFAULT NULL,
  `estado` VARCHAR(255) NULL DEFAULT NULL,
  `codigo_postal` VARCHAR(255) NULL DEFAULT NULL,
  `pais` VARCHAR(255) NULL DEFAULT NULL,
  `activo` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`id_contacto`),
  INDEX `fk_contacto_usuario1_idx` (`usuario_id_usuario` ASC),
  CONSTRAINT `fk_contacto_usuario1`
    FOREIGN KEY (`usuario_id_usuario`)
    REFERENCES `posesio_app_user_`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `posesio_app_user_`.`contrato`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `posesio_app_user_`.`contrato` ;

CREATE TABLE IF NOT EXISTS `posesio_app_user_`.`contrato` (
  `id_contrato` INT NOT NULL AUTO_INCREMENT,
  `usuario_id_usuario` INT NOT NULL,
  `propiedad_id_propiedad` INT NOT NULL,
  `contacto_id_contacto` BIGINT NOT NULL,
  `id_fiador` BIGINT NULL DEFAULT NULL,
  `validez_fiscal` TINYINT(1) NOT NULL,
  `fecha_inicio` DATE NOT NULL,
  `fecha_fin` DATE NOT NULL,
  `fecha_corte` DATE NOT NULL,
  `periodicidad` VARCHAR(255) NOT NULL,
  `adeudo_anterior` DECIMAL(15,2) NULL DEFAULT NULL,
  `monto` DECIMAL(15,2) NOT NULL,
  `tasa_iva` DECIMAL(15,2) NOT NULL,
  `iva` DECIMAL(15,2) NOT NULL,
  `subtotal` DECIMAL(15,2) NOT NULL,
  `retencion_isr` DECIMAL(15,2) NOT NULL,
  `retencion_iva` DECIMAL(15,2) NOT NULL,
  `total` DECIMAL(15,2) NOT NULL,
  `multa_moratoria` DECIMAL(15,2) NOT NULL,
  `dias_multa` INT NOT NULL,
  `tasa_interes` VARCHAR(45) NOT NULL,
  `dias_interes` INT NOT NULL,
  `porcentaje_tasa_interes` DECIMAL(10,2) NOT NULL,
  `activo` TINYINT(1) NOT NULL,
  `comentarios` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id_contrato`, `propiedad_id_propiedad`, `contacto_id_contacto`),
  INDEX `fk_contrato_propiedad1_idx` (`propiedad_id_propiedad` ASC),
  INDEX `fk_contrato_contacto1_idx` (`contacto_id_contacto` ASC),
  INDEX `fk_contrato_contacto2_idx` (`id_fiador` ASC),
  INDEX `fk_contrato_usuario1_idx` (`usuario_id_usuario` ASC),
  CONSTRAINT `fk_contrato_propiedad1`
    FOREIGN KEY (`propiedad_id_propiedad`)
    REFERENCES `posesio_app_user_`.`propiedad` (`id_propiedad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contrato_contacto1`
    FOREIGN KEY (`contacto_id_contacto`)
    REFERENCES `posesio_app_user_`.`contacto` (`id_contacto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contrato_contacto2`
    FOREIGN KEY (`id_fiador`)
    REFERENCES `posesio_app_user_`.`contacto` (`id_contacto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_contrato_usuario1`
    FOREIGN KEY (`usuario_id_usuario`)
    REFERENCES `posesio_app_user_`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `posesio_app_user_`.`datos_fiscales`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `posesio_app_user_`.`datos_fiscales` ;

CREATE TABLE IF NOT EXISTS `posesio_app_user_`.`datos_fiscales` (
  `id_datos_fiscales` BIGINT NOT NULL AUTO_INCREMENT,
  `usuario_id_usuario` INT NOT NULL,
  `ruta_logo` VARCHAR(255) NULL DEFAULT NULL,
  `persona` VARCHAR(10) NULL DEFAULT NULL,
  `razon_social` VARCHAR(255) NULL DEFAULT NULL,
  `rfc` VARCHAR(13) NULL DEFAULT NULL,
  `calle` VARCHAR(255) NULL DEFAULT NULL,
  `numero_exterior` VARCHAR(50) NULL DEFAULT NULL,
  `numero_interior` VARCHAR(50) NULL DEFAULT NULL,
  `colonia` VARCHAR(255) NULL DEFAULT NULL,
  `municipio` VARCHAR(255) NULL DEFAULT NULL,
  `estado` VARCHAR(255) NULL DEFAULT NULL,
  `codigo_postal` VARCHAR(255) NULL DEFAULT NULL,
  `pais` VARCHAR(255) NULL DEFAULT NULL,
  `ruta_cer` VARCHAR(255) NULL DEFAULT NULL,
  `ruta_key` VARCHAR(255) NULL DEFAULT NULL,
  `llave_privada` VARCHAR(255) NULL DEFAULT NULL,
  `licencia` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id_datos_fiscales`),
  CONSTRAINT `fk_datos_fiscales_usuario1`
    FOREIGN KEY (`id_datos_fiscales`)
    REFERENCES `posesio_app_user_`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `posesio_app_user_`.`recibo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `posesio_app_user_`.`recibo` ;

CREATE TABLE IF NOT EXISTS `posesio_app_user_`.`recibo` (
  `id_recibo` INT NOT NULL AUTO_INCREMENT,
  `usuario_id_usuario` INT NOT NULL,
  `contrato_id_contrato` INT NOT NULL,
  `contrato_propiedad_id_propiedad` INT NOT NULL,
  `contrato_contacto_id_contacto` BIGINT NOT NULL,
  `fecha_corte` DATETIME NOT NULL,
  `fecha_inicio_recibo` DATETIME NOT NULL,
  `fecha_fin_recibo` DATETIME NOT NULL,
  `monto` DECIMAL(15,2) NOT NULL,
  `tasa_iva` DECIMAL(15,2) NOT NULL,
  `iva` DECIMAL(15,2) NOT NULL,
  `subtotal` DECIMAL(15,2) NOT NULL,
  `retencion_isr` DECIMAL(15,2) NOT NULL,
  `retencion_iva` DECIMAL(15,2) NOT NULL,
  `total` DECIMAL(15,2) NOT NULL,
  `validez_fiscal` TINYINT(1) NOT NULL COMMENT 'No se refiere a el estatus de \"timbrada\" sino al hecho de si es una factura o un recibo \"normal\"',
  `no_cuenta` VARCHAR(45) NOT NULL DEFAULT 'No Identificado',
  `metodo_pago` VARCHAR(100) NOT NULL DEFAULT 'No Identificado',
  `fecha_update` DATETIME NOT NULL,
  `folio_factura` INT NULL DEFAULT NULL,
  `folio_recibo` INT NULL DEFAULT NULL,
  `estatus_recibo` TINYINT(1) NOT NULL COMMENT '0 sin pagar, 1 pagado',
  `cancelado` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id_recibo`, `contrato_id_contrato`, `contrato_propiedad_id_propiedad`, `contrato_contacto_id_contacto`),
  INDEX `fk_pago_contrato1_idx` (`contrato_id_contrato` ASC, `contrato_propiedad_id_propiedad` ASC, `contrato_contacto_id_contacto` ASC),
  INDEX `fk_recibo_usuario1_idx` (`usuario_id_usuario` ASC),
  CONSTRAINT `fk_pago_contrato1`
    FOREIGN KEY (`contrato_id_contrato` , `contrato_propiedad_id_propiedad` , `contrato_contacto_id_contacto`)
    REFERENCES `posesio_app_user_`.`contrato` (`id_contrato` , `propiedad_id_propiedad` , `contacto_id_contacto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_recibo_usuario1`
    FOREIGN KEY (`usuario_id_usuario`)
    REFERENCES `posesio_app_user_`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `posesio_app_user_`.`concepto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `posesio_app_user_`.`concepto` ;

CREATE TABLE IF NOT EXISTS `posesio_app_user_`.`concepto` (
  `id_concepto` INT NOT NULL AUTO_INCREMENT,
  `usuario_id_usuario` INT NOT NULL,
  `recibo_id_recibo` INT NOT NULL,
  `recibo_contrato_id_contrato` INT NOT NULL,
  `recibo_contrato_propiedad_id_propiedad` INT NOT NULL,
  `recibo_contrato_contacto_id_contacto` BIGINT NOT NULL,
  `descripcion` VARCHAR(255) NOT NULL,
  `monto` DECIMAL(15,2) NOT NULL,
  PRIMARY KEY (`id_concepto`, `recibo_id_recibo`, `recibo_contrato_id_contrato`, `recibo_contrato_propiedad_id_propiedad`, `recibo_contrato_contacto_id_contacto`),
  INDEX `fk_concepto_recibo1` (`recibo_id_recibo` ASC, `recibo_contrato_id_contrato` ASC, `recibo_contrato_propiedad_id_propiedad` ASC, `recibo_contrato_contacto_id_contacto` ASC),
  INDEX `fk_concepto_usuario1_idx` (`usuario_id_usuario` ASC),
  CONSTRAINT `fk_concepto_recibo1`
    FOREIGN KEY (`recibo_id_recibo` , `recibo_contrato_id_contrato` , `recibo_contrato_propiedad_id_propiedad` , `recibo_contrato_contacto_id_contacto`)
    REFERENCES `posesio_app_user_`.`recibo` (`id_recibo` , `contrato_id_contrato` , `contrato_propiedad_id_propiedad` , `contrato_contacto_id_contacto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_concepto_usuario1`
    FOREIGN KEY (`usuario_id_usuario`)
    REFERENCES `posesio_app_user_`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `posesio_app_user_`.`factura`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `posesio_app_user_`.`factura` ;

CREATE TABLE IF NOT EXISTS `posesio_app_user_`.`factura` (
  `recibo_id_recibo` INT NOT NULL,
  `usuario_id_usuario` INT NOT NULL,
  `recibo_contrato_id_contrato` INT NOT NULL,
  `recibo_contrato_propiedad_id_propiedad` INT NOT NULL,
  `recibo_contrato_contacto_id_contacto` BIGINT NOT NULL,
  `id_factura` BIGINT(20) NOT NULL,
  `xml` TEXT NOT NULL,
  `version` VARCHAR(3) NOT NULL,
  `folio` INT(50) NOT NULL,
  `uuid` TEXT NOT NULL,
  `rfc_emisor` VARCHAR(15) NOT NULL,
  `rfc_receptor` VARCHAR(15) NOT NULL,
  `total` DECIMAL(15,2) NOT NULL,
  `cadena_original` TEXT NOT NULL,
  `sello` TEXT NOT NULL,
  `qr` TEXT NOT NULL,
  PRIMARY KEY (`recibo_id_recibo`, `recibo_contrato_id_contrato`, `recibo_contrato_propiedad_id_propiedad`, `recibo_contrato_contacto_id_contacto`, `id_factura`),
  INDEX `fk_factura_usuario1_idx` (`usuario_id_usuario` ASC),
  CONSTRAINT `fk_factura_recibo1`
    FOREIGN KEY (`recibo_id_recibo` , `recibo_contrato_id_contrato` , `recibo_contrato_propiedad_id_propiedad` , `recibo_contrato_contacto_id_contacto`)
    REFERENCES `posesio_app_user_`.`recibo` (`id_recibo` , `contrato_id_contrato` , `contrato_propiedad_id_propiedad` , `contrato_contacto_id_contacto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_factura_usuario1`
    FOREIGN KEY (`usuario_id_usuario`)
    REFERENCES `posesio_app_user_`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `posesio_app_user_`.`pago`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `posesio_app_user_`.`pago` ;

CREATE TABLE IF NOT EXISTS `posesio_app_user_`.`pago` (
  `id_pago` BIGINT NOT NULL AUTO_INCREMENT,
  `usuario_id_usuario` INT NOT NULL,
  `recibo_id_recibo` INT NULL DEFAULT NULL,
  `recibo_contrato_id_contrato` INT NOT NULL,
  `recibo_contrato_propiedad_id_propiedad` INT NOT NULL,
  `recibo_contrato_contacto_id_contacto` BIGINT NOT NULL,
  `fecha_pago` DATETIME NOT NULL,
  `forma_pago` VARCHAR(45) NOT NULL,
  `banco` VARCHAR(100) NULL DEFAULT NULL,
  `num_cheque` VARCHAR(100) NULL DEFAULT NULL,
  `abono` DECIMAL(15,2) NOT NULL,
  `comentarios` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id_pago`, `recibo_contrato_id_contrato`, `recibo_contrato_propiedad_id_propiedad`, `recibo_contrato_contacto_id_contacto`),
  INDEX `fk_pago_recibo1` (`recibo_id_recibo` ASC, `recibo_contrato_id_contrato` ASC, `recibo_contrato_propiedad_id_propiedad` ASC, `recibo_contrato_contacto_id_contacto` ASC),
  INDEX `fk_pago_usuario1_idx` (`usuario_id_usuario` ASC),
  CONSTRAINT `fk_pago_recibo1`
    FOREIGN KEY (`recibo_id_recibo` , `recibo_contrato_id_contrato` , `recibo_contrato_propiedad_id_propiedad` , `recibo_contrato_contacto_id_contacto`)
    REFERENCES `posesio_app_user_`.`recibo` (`id_recibo` , `contrato_id_contrato` , `contrato_propiedad_id_propiedad` , `contrato_contacto_id_contacto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pago_usuario1`
    FOREIGN KEY (`usuario_id_usuario`)
    REFERENCES `posesio_app_user_`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `posesio_app_user_`.`duenos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `posesio_app_user_`.`duenos` ;

CREATE TABLE IF NOT EXISTS `posesio_app_user_`.`duenos` (
  `id_dueno` BIGINT NOT NULL AUTO_INCREMENT,
  `usuario_id_usuario` INT NOT NULL,
  `persona` VARCHAR(10) NULL DEFAULT NULL,
  `razon_social` VARCHAR(255) NULL DEFAULT NULL,
  `rfc` VARCHAR(13) NULL DEFAULT NULL,
  `calle` VARCHAR(255) NULL DEFAULT NULL,
  `numero_exterior` VARCHAR(50) NULL DEFAULT NULL,
  `numero_interior` VARCHAR(50) NULL DEFAULT NULL,
  `colonia` VARCHAR(255) NULL DEFAULT NULL,
  `municipio` VARCHAR(255) NULL DEFAULT NULL,
  `estado` VARCHAR(255) NULL DEFAULT NULL,
  `codigo_postal` VARCHAR(255) NULL DEFAULT NULL,
  `pais` VARCHAR(255) NULL DEFAULT NULL,
  `ruta_cer` VARCHAR(255) NULL DEFAULT NULL,
  `ruta_key` VARCHAR(255) NULL DEFAULT NULL,
  `llave_privada` VARCHAR(255) NULL DEFAULT NULL,
  `licencia` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id_dueno`),
  INDEX `fk_duenos_usuario1_idx` (`usuario_id_usuario` ASC),
  CONSTRAINT `fk_duenos_usuario1`
    FOREIGN KEY (`usuario_id_usuario`)
    REFERENCES `posesio_app_user_`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
